name: Release build

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    - name: Setup Gradle
      uses: gradle/wrapper-validation-action@v1
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        gradle-executable: ./gradlew
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Dynamic Surroundings
        path: |
          build/libs/
          !build/libs/*-dev.jar
